Fix requests UTF8 encoding for special characters
dopecodez/Wikipedia pull request #12
Opened 2021-03-25 18:47 UTC by bumbummen99

Add workaround to encode URL as UTF-8 fixing URLs that include special characters such as umlauts like `ö`

Source: https://github.com/node-fetch/node-fetch/issues/245

2021-03-25 19:15 UTC, bumbummen99 commented
Checks fail due to `CC_TEST_REPORTER_ID` not being available to forks.

2021-03-26 06:51 UTC, dopecodez commented
Ah, thanks for pointing that out @bumbummen99 .

I read through the reasons for this https://github.community/t/make-secrets-available-to-builds-of-forks/16166 and it doesn't look like there's gonna be a solution from github anytime soon. I'll have to make the secret public or do any of the workarounds mentioned in the ticket. I'll also check out how other open source libraries which have moved to github actions are handling the problem.

2021-03-26 06:54 UTC, dopecodez requested changes

2021-03-26 06:54 UTC, dopecodez commented on source/request.ts
>  import { URLSearchParams } from 'url';
```suggestion
import { URLSearchParams, URL } from 'url';
```

2021-03-26 06:54 UTC, dopecodez commented on source/request.ts
> +import { URL } from 'url';
Let's have both the imports in a single import.

2021-03-26 07:02 UTC, dopecodez commented
Other than that, the changes look good, I tested out your fork and its working fine. Thanks for the PR, @bumbummen99 🏅

2021-03-26 07:03 UTC, dopecodez commented on source/request.ts
> +import { URL } from 'url';
```suggestion

```

2021-03-26 07:04 UTC, merged

2021-03-26 18:33 UTC, bumbummen99 commented
> Other than that, the changes look good, I tested out your fork and its working fine. Thanks for the PR, @bumbummen99

Can we please get a new release tag including the fix? :smiley:

2021-03-26 19:22 UTC, dopecodez commented
Apologies @bumbummen99. I was planning on releasing it later but got caught up with work. The release is published here: https://github.com/dopecodez/Wikipedia/releases/tag/v1.0.5 and should be available in the npm store.